# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='billing_saved',
            field=models.BooleanField(default=False),
        ),
    ]
