# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0004_remove_job_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
