# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0005_auto_20160428_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
