# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 23:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0008_auto_20160503_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 5, 3, 23, 31, 48, 885676, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 3, 23, 32, 1, 63573, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
