# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0012_job_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='charge_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
