# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0013_auto_20160505_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
