# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0015_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pickup_for',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
