# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0016_job_pickup_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
