# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0018_job_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='report_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='strike_mover',
            field=models.BooleanField(default=False),
        ),
    ]
