# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0019_auto_20160511_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='muver_api.Job'),
            preserve_default=False,
        ),
    ]
