# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0021_job_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
