# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0023_auto_20160513_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
