# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0026_job_time_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='point_a',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='point_b',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
