# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 00:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muver_api', '0027_auto_20160514_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='point_a',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='job',
            name='point_b',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
